### PR TITLE
Added blink, color, size, center SkypeMsg Format

### PR DESCRIPTION
**Pull request by Derpolino**
```py
from skpy import Skype
from skpy import SkypeMsg
sk = Skype("XXX", "XXX")
ch = sk.chats["XXX"]
```

## Blink Format !
```py
ch.sendMsg(SkypeMsg.blink("Blink Format !"), rich=True)
```
Result : `<blink>Blink Format !</blink>`

## Color Format !
```py
ch.sendMsg(SkypeMsg.color("Color Format !", "#ff0000"), rich=True)
```
Result : `<font color="#ff0000">Color Format !</font>`

## Size Format !
```py
ch.sendMsg(SkypeMsg.size("100px !", "100"), rich=True)
```
Result : `<font size="#ff0000">100px</font>`

## Center Format !
```py
ch.sendMsg(SkypeMsg.center("Center format !") , rich=True)
```
Result : `<center>Center format !</center>`

### CODE REVIEW

**Comment by Derpolino** [comment]
btw, `<font face="verdana">Verdana</font>` doesn't work

**Comment by OllieTerrance** [comment]
Hmm, the only one I see working on Skype for Web is font colour:

Message format testing

I guess the rest are Windows-specific?

As this is supposed to be based on Skype HTTP, I'm hesitant on adding client-specific formatting (particularly as the desktop clients are likely to move over to the HTTP APIs at some point too).

**Comment by Derpolino** [comment]
Yes, the rest are Windows-specific :/

18e07cb7689ee0abadad2e83da910226

But blink worked on web, it's strange

**Comment by OllieTerrance** [comment]
I think we can add a colour method, I'll hold off on the rest for now.

(You can of course still send other formatting by entering the HTML manually in a call to `sendMsg()`.)

I've also added [some notes on compatibility](http://sandbox.t.allofti.me/skpy/misc.html#message-formatting) to the docs.

**Pull request closed without merging**
