### PR TITLE
Error-handling messages

### PR DESCRIPTION
**Pull request by leondealmeida**
Augments and adds error messages to scenarios identified in the code. References #29.

### CODE REVIEW

**Comment by OllieTerrance** [comment]
This is a somewhat heavy addition for what is essentially adding a bit more text to the exceptions...

I'm not sure about overly long exception messages -- perhaps it might be better to state something general but clear, and explain the exact messages and causes in the docs instead.

> `tField` being `None` does allow processing to continue in case there is no error message in the response text.

Presumably not processing the login -- we're just explicitly raising `SkypeAuthException`, instead of accidentally causing an `AttributeError` later on?

**Comment by leondealmeida** [comment]
> This is a somewhat heavy addition for what is essentially adding a bit more text to the exceptions...

I also refactored some of the code into their own functions so it's easier to debug and isolate issues - not necessary, though I feel it's a better approach. Things like the `tField` being None and allowing processing to start, to then break when it tries using `tField.get('value')` may indicate specific issues, which are easier to trap (and process) if they're isolated on their own code blocks.

> long exception messages -- perhaps it might be better to state something general but clear

I may have gone over the top - in my experience with the library, it'd have been many times better to have something very specific to look for or do rather than trying to figure out and learn that _any auth issue requires me to check if there's something wrong with my account_. I think the more specific the messages are, the better - though long ones should probably be avoided.

> Presumably not processing the login -- we're just explicitly raising `SkypeAuthException`, instead of accidentally causing an `AttributeError` later on?

Yes. One is a handled error, the other is an error due to a situation the code is not expecting. Once we trapped that, we (probably?) know what has happened, and can provide a message stating why it is that the code can't continue processing.

**Comment by OllieTerrance** [comment]
I've fiddled with the exceptions a bit so `SkypeAuthException` should always be used.  There may be some refactoring to come later, though splitting this out into different methods is a bit overkill when they're only used in one place.

> it'd have been many times better to have something very specific to look for or do rather than trying to figure out and learn that _any auth issue requires me to check if there's something wrong with my account_

Unfortunately that applies to most of the library -- assuming a feature is implemented correctly locally, chances are a server error through SkPy will be reproducible on Skype for Web.  Perhaps something prominent in the docs or a CONTRIBUTING.md is in order...

**Comment by leondealmeida** [comment]
Nice, sounds good.

**Pull request closed without merging**
